---
title: "HAN Bedrijfskunde"
subtitle: "Semester 1 2018/19"
author: "Docenten: Witek ten Hove en David Hartsuiker"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Dit is het platform voor B-cluster Onderzoek van de opleiding HAN Bedrijfskunde. Hier plaatsen we materiaal dat specifiek gericht is aan studenten HAN Bedrijfskunde die in dit semester deze module volgen.

Voor alle algemene, propedeuse-brede informatie verwijzen we naar het materiaal op <a href="https://onderwijsonline.han.nl/elearning/content/pNWMKBDj" target="_blank">Onderwijs Online</a>. Mocht je vragen hebben waarvoor je de antwoorden niet online hebt gevonden, dan kun je mailen naar: <a href="mailto:witek.tenhove@han.nl?Subject=B-cluster%20onderzoek%20" target="_top">Witek ten Hove</a> of <a href="mailto:david.hartsuiker@han.nl?Subject=B-cluster%20onderzoek%20" target="_top">David Hartsuiker</a>

## Teams { .tabset}

### BKA-B03

Ieder team houdt de voortgang bij in een online notebook. Volg onderstaande links voor de afzonderlijke documenten:

- <a href="" target="_blank">Team 1</a>
- <a href="" target="_blank">Team 2</a>
- <a href="" target="_blank">Team 3</a>
- <a href="" target="_blank">Team 4</a>
- <a href="http://mvoost.simplesite.com/" target="_blank">Team 5</a>
- <a href="" target="_blank">Team 6</a>
- <a href="" target="_blank">Team 7</a>
- <a href="" target="_blank">Team 8</a>
- <a href="" target="_blank">Team 9</a>
- <a href="" target="_blank">Team 10</a>

### BKN-B07

Ieder team houdt de voortgang bij in een online notebook. Volg onderstaande links voor de afzonderlijke documenten:

- <a href="" target="_blank">Team 1</a>
- <a href="" target="_blank">Team 2</a>
- <a href="" target="_blank">Team 3</a>
- <a href="" target="_blank">Team 4</a>
- <a href="" target="_blank">Team 5</a>
- <a href="" target="_blank">Team 6</a>
- <a href="" target="_blank">Team 7</a>
- <a href="" target="_blank">Team 8</a>
- <a href="" target="_blank">Team 9</a>
- <a href="" target="_blank">Team 10</a>