---
title: "Probleemverkenning"
output: html_document
---

### Voorbereiding
Voor het werkcollege heb je de beschrijving van de module bestudeerd (zie <a href="https://onderwijsonline.han.nl/elearning/content/pNWMKBDj" target="_blank">Onderwijs Online</a>).

### Opdracht

Het thema voor dit semester is **online vertrouwen**. Dit wetenschappelijke <a href="https://drive.google.com/open?id=1De98mxGp_90TA2JH0zWqnSrPm1lnFS8x" target="_blank">artikel</a> bespreekt de factoren die vertrouwen verhogen of juist verlagen bij online bezoekers van een website.

Ieder lid van elk team zoekt nog een artikel binnen hetzelfde thema op. Dit artikel dient later ter inspiratie voor de bepaling van de onderzoeksvraag en onderzoeksopzet. In hun notebook beschrijven de teams de relevantie van het thema voor hun vakgebied, welke artikelen en onderzoeksvraagstukken ze hebben gevonden en wat de belangrijkste conclusies zijn. Uiteindelijk bedenkt ieder team één nieuwe onderzoeksvraag en neemt die mee naar het volgende werkcollege.

Het notebook moet bestaan uit een online document (website, blog, etc. of <a href="https://applieddigitalskills.withgoogle.com/c/middle-and-high-school/en/research-and-develop-a-topic/explore-a-topic-with-research-and-collaboration/choose-a-research-topic.html" target="_blank">dit</a>) en aantrekkelijk zijn vormgegeven (voor de lezer). De url van het document stuur je naar de docent. Deze plaatst alle urls op de [startpagina](https://hanbedrijfskunde.github.io/bon/index.html).

### Inspiratie

- <a href="https://witusj.github.io/b-cluster/presentation/index.html" target="_blank">Startpresentatie</a>
- Dina Ribbink, Allard C.R. van Riel, Veronica Liljander, Sandra Streukens, (2004) "Comfort your online customer: quality, trust and loyalty on the internet", Managing Service Quality: An International Journal, Vol. 14 Issue: 6, pp.446-456, https://doi.org/10.1108/09604520410569784
- <a href="https://applieddigitalskills.withgoogle.com/c/middle-and-high-school/en/research-and-develop-a-topic/overview.html" target="_blank">Tutorial</a> online onderzoeksrapportage (Google)
- Roghanizad, M. M., & Neufeld, D. J. (2015). Intuition, risk, and the formation of online trust. Computers in Human Behavior, 50, 489-498.


<hr>

<div class="resp-container">
  <iframe class="resp-iframe" src="https://www.youtube.com/embed/3vyheXBPSsg" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
<br>
<div class="resp-container">
  <iframe class="resp-iframe" src="https://www.youtube.com/embed/RZcfmA1l6cE" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
