---
title: "Afbakening onderzoek"
output: html_document
---

### Voorbereiding
Ieder **lid** van ieder team heeft een wetenschappelijk artikel over het onderzoeksthema aangeleverd. In hun notebook beschrijven de teams de relevantie van het thema voor hun vakgebied, welke artikelen en onderzoeksvraagstukken ze hebben gevonden en wat de belangrijkste conclusies zijn. Ieder team heeft één nieuwe onderzoeksvraag bedacht en neemt deze mee naar het werkcollege.

### Opdracht

We zijn nog steeds bij de eerste stap van het <a href="https://en.wikipedia.org/wiki/Cross-industry_standard_process_for_data_mining" target="_blank">data analyse proces</a>, maar hebben inmiddels wel een onderzoeksthema. Door een duidelijke onderzoeksvraag te formuleren krijgt het onderzoek focus.

Tijdens het werkcollege worden alle aangeleverde onderzoeksvragen doorgenomen. Er worden criteria afgesproken waarmee de kwaliteit van de vragen kan worden gemeten en de beste vraag wordt bepaald. Deze vraag zal worden gebruikt als centrale onderzoeksvraag voor alle teams. Bovendien worden afspraken gemaakt over deelvragen.
<hr>

<div class="resp-container">
  <iframe class="resp-iframe" src="https://docs.google.com/presentation/d/e/2PACX-1vQ2_72qzfCBiZpuS98PUzLodLo2u-rHDNx1j0Il-a2Dn1MT5MSLfP6Ut6qONmQ9ja3qN9x8iuSP65kw/embed?start=true&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>
</div>

<hr>
Ieder team start een online document met daarin hun onderzoeksplan. De structuur is als volgt:

1. Aanleiding en wetenschappelijke inzichten (o.b.v. verzamelde literatuur)
2. Practische doelstelling
3. Centrale vraag : welke vraag wordt dadelijk in de conclusie beantwoord?
4. Deelvragen : welke aspecten onderzoek je om de centrale vraag te kunnen beantwoorden?
5. Onderzoeksmethode: kwantitatief onderzoek
6. Dataverzamelingsinstrument : enquetes
7. Populatie en steekproefmethode
8. Beperkingen en randvoorwaarden
9. Tijdsplanning van het onderzoek

Verder geldt het volgende:

- Omvang projectplan: ca. 2 x A4
- In het notebook wordt een koppeling geplaatst naar het onderzoeksplan
- Ieder teamlid beschrijft zijn bijdrage aan de kwaliteit van het onderzoeksplan
- TIP: gebruik de wetenschappelijke artikelen als inspiratie voor bovenstaande

<hr>

### Documentatie
Werkbladen: <a href="https://docs.google.com/presentation/d/1HxvxHEieafIOUuWo9YCdkzd9jEv8IkQ3TCjlfvAupgo/edit?usp=sharing" target="-blank">BKA-B03</a>, <a href="https://docs.google.com/presentation/d/1mTSmeD4A1KRkcOjGUOqHUXVaiYw5nmgBwNQlNs0Jjzs/edit?usp=sharing" target="-blank">BKN-B07</a>

<div class="resp-container">
  <iframe class="resp-iframe" src="https://docs.google.com/presentation/d/e/2PACX-1vQw_NoRUSAAWCmgvZ9-G4SMElzbxXs9Mp6xdiYxnkNjwAmjyvErzVPruU0JL5d2AaXDlL3t03BwX8a3/embed?start=false&loop=false&delayms=3000" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

<hr>
<div class="resp-container">
  <iframe class="resp-iframe" src="https://www.youtube.com/embed/QauomrFcrXk" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>