---
title: "Kwantitatief onderzoek / Enquete research"
output: html_document
---

### Voorbereiding
Vorige week heb je met je team de eerste opzet van het onderzoeksplan afgemaakt. Daarin staan onder andere de centrale vraag en de set van deelvragen. De link naar dit online document in het notebook geplaatst.

### Opdracht

De volgende stap in het data-analyse proces betreft het verzamelen van data. De data moet van voldoende kwaliteit zijn en uiteindelijk de juiste informatie opleveren om de onderzoeksvraag te beantwoorden.

In dit geval gaan we de data direct bij respondenten ophalen m.b.v. een enquête. Het opstellen van een enquête is een tijdrovende activiteit en eenmaal uitgezet kan het proces niet meer worden onderbroken en aangepast. Als dus in deze fase fouten worden gemaakt, betekent dit dat de data slecht of zelfs onbruikbaar is en dat het onderzoek is mislukt.

Dit stadium in het proces vereist daarom de hoogste mate van aandacht en concentratie. Tijdens het werkcollege werk je met je team een aantal passende enquêtevragen uit. Alle vragen worden samengevoegd en wederom wordt met de groep bepaald met welke vragen een zo volledig en duidelijk mogelijk antwoord wordt verkregen op de onderzoeksvraag.
<hr>
<div class="resp-container">
<iframe class="resp-iframe" allowfullscreen="true" frameborder="0" mozallowfullscreen="true" src="https://docs.google.com/presentation/d/e/2PACX-1vQ2_72qzfCBiZpuS98PUzLodLo2u-rHDNx1j0Il-a2Dn1MT5MSLfP6Ut6qONmQ9ja3qN9x8iuSP65kw/embed?start=false&loop=false&delayms=3000" webkitallowfullscreen="true"></iframe>
</div>
<hr>
Met je team stel je een vragenlijst op. Wat betreft de kwaliteit dient met volgende rekening te worden gehouden (de nummers verwijzen naar de betreffende onderdelen uit het studieboek):

- Voldoet aan de basiseisen (7.4.1)
- Vraagsoorten : enkelvoudig / meervoudig / halfopen / schaalvragen
- De antwoordcategorieën voldoen aan de voorwaarden (7.5)
- Over alle deelvragen zijn enquetevragen gesteld.
- Complexe begrippen zijn geoperationaliseerd in dimensies, indicatoren en items (7.3)
- Alle meetniveaus: nominaal / ordinaal / scale zijn aanwezig (7.7)
- Te beantwoorden in maximaal 10 minuten
- Bovenstaande verwerk je in een <a href="http://www.medicine.mcgill.ca/epidemiology/joseph/pbelisle/CodebookCookbook/CodebookCookbook.pdf" target="_blank">codeboek</a>
- In het notebook staat een koppeling naar het codeboek
- Ieder teamlid beschrijft zijn bijdrage aan de kwaliteit van de vragenlijst
- TIP: gebruik de wetenschappelijke artikelen als inspiratie voor bovenstaande

### Notities

<a href="https://docs.google.com/presentation/d/e/2PACX-1vQzlWI0JdY1FUYDOaCy_ra2b55cX3CoCrSf6pSfMcAydz6szTAk33xW5lVBFruO-0e3Wjz1HrbIc6F7/pub?start=false&loop=false&delayms=3000" target="_blank">Link </a>naar slides Witek

### Documentatie
- Madacsi, H. (januari, 2018). De invloed van demografische factoren op de relatie tussen de tevredenheid over orderprocessen, gepercipieerde waarde en herhaalaankoop intentie in een online omgeving. Geraadpleegd op 13 september 2018, van http://dspace.ou.nl/bitstream/1820/9536/1/Madacsi%20H%20MM9906%20AF%20scriptie.pdf

<hr>
<div class="resp-container">
  <iframe class="resp-iframe" src="https://docs.google.com/presentation/d/e/2PACX-1vQyCn8P63KQRzq_BHRqw_kEyg8c4Qr5JmxFWLuq_4gFwPj5thky6NSwHaTUms0c0Tm8jW2tM9fiA1h3/embed?start=false&loop=false&delayms=3000" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

<hr>
<div class="resp-container">
<iframe class="resp-iframe" src="https://www.youtube.com/embed/i-5U9F-KzBY" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>

<hr>
<div class="resp-container">
  <iframe class="resp-iframe" src="https://www.youtube.com/embed/pId_SIfO8mQ" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen></iframe>
</div>
